version: "3.9"
services:
  rabbit:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
  deals:
    image: "ghcr.io/sharonfabin/deals-service"
    ports:
      - "9001:9001"
    env_file:
      - deals.env
    depends_on:
      - "rabbit"
    volumes:
      - ./security/certbot/conf/:/etc/nginx/ssl/:ro
  ui:
    image: "ghcr.io/sharonfabin/ui"
    ports:
      - "81:80"
    env_file:
      - ui.env
    depends_on:
      - "deals"
  nginx:
    image: "ghcr.io/sharonfabin/nginx"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro
      - ./security/certbot/www:/var/www/certbot/:ro
      - ./security/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./security/certbot/www/:/var/www/certbot/:rw
      - ./security/certbot/conf/:/etc/letsencrypt/:rw
