version: "3.9"
services:
  rabbit:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"
  deals:
    image: "ghcr.io/sharonfabin/deals-service"
    ports:
      - "9001:9001"
    env_file:
      - deals.env
    depends_on:
      - "rabbit"
