version: "3.9"
services:
  rabbit:
    image: "rabbitmq:management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
  deals:
    image: "ghcr.io/sharonfabin/deals-service"
    ports:
      - "9001:9001"
    env_file:
      - deals.env
    depends_on:
      - "rabbit"
    volumes:
      - ./security/certbot/conf/:/etc/nginx/ssl/:ro
  ui:
    image: "ghcr.io/sharonfabin/ui"
    ports:
      - "3000:3000"
    env_file:
      - ui.env
    depends_on:
      - "deals"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.6.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - elastic.env
    restart: unless-stopped
    volumes:
      - ./Elastic/data/:/usr/share/elasticsearch/data:rw
      - ./Elastic/certs/:/usr/share/elasticsearch/config/certs:rw
    mem_limit: 1g
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d:ro
      - ./security/certbot/www:/var/www/certbot/:ro
      - ./security/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./security/certbot/www/:/var/www/certbot/:rw
      - ./security/certbot/conf/:/etc/letsencrypt/:rw
