interface FullProperty {
  source: string;
  sourceId: string;
  insertDate: string;
  latitude: number;
  longitude: number;
  addressNumber: string;
  addressName: string;
  addressSuffix: string;
  unitNumber: string | null;
  address: string;
  city: string;
  zipcode: string;
  county: string;
  state: string;
  floodZone: string;
  neighborhood: string;
  propertyType: string;
  bedrooms: number;
  fullBathrooms: number;
  halfBathrooms: number;
  totalBathrooms: number;
  lotSize: number;
  buildingArea: number;
  yearBuilt: string;
  floors: number;
  pool: boolean;
  garages: number;
  salesStatus: string;
  salesDate: string;
  salesListingPrice: number;
  salesClosingPrice: number;
  salesDaysOnMarket: number;
  rentsStatus: string | null;
  rentsDate: string | null;
  rentsListingPrice: number | null;
  rentsClosingPrice: number | null;
  rentsDaysOnMarket: number | null;
  tax: number | null;
}

export default FullProperty;
