interface AnalyzedProperty {
  property: Property;
  CompsData: Property[];
  market_id: string;
  source_id: string;
  buybox_id: string;
  update_date: string;
  listing_price: number;
  is_opp: boolean;
  opp_name: string;
  sales_comps: number;
  arv_ids: string[];
  arv: number;
  n_sales: number;
  expenses_total: number;
  margin: number;
  margin_percentage: number;
  cents_on_dollar: number;
  ltv: number;
  n_rents: number;
  operational_expenses_total: number;
  cap_rate: number;
  images: string[];
  listing_status: string;
  source: string;
  address: string;
  city: string;
  zipcode: string;
  state: string;
  neighborhood: string;
  arv_percentage: number;
}

interface Property {
  source: string;
  insert_date: string;
  latitude: number;
  longitude: number;
  address_number: string;
  address_name: string;
  address_suffix: string;
  unit_number: string;
  address: string;
  city: string;
  zipcode: string;
  county: string;
  state: string;
  flood_zone: string;
  neighborhood: string;
  property_type: string;
  bedrooms: number;
  full_bathrooms: number;
  half_bathrooms: number;
  total_bathrooms: number;
  lot_size: number;
  building_area: number;
  year_built: string;
  floors: number;
  pool: boolean;
  garages: number;
  sales_status: string;
  sales_date: string;
  sales_listing_price: number;
  sales_closing_price: string;
  sales_days_on_market: number;
  rents_status: string;
  rents_date: string;
  rents_listing_price: string;
  rents_closing_price: string;
  rents_days_on_market: string;
}

export default AnalyzedProperty;
export type { Property };
