interface FullProperty {
    source: string;
    source_id: string;
    insert_date: string;
    latitude: number;
    longitude: number;
    address_number: string;
    address_name: string;
    address_suffix: string;
    unit_number: string | null;
    address: string;
    city: string;
    zipcode: string;
    county: string;
    state: string;
    flood_zone: string;
    neighborhood: string;
    property_type: string;
    bedrooms: number;
    full_bathrooms: number;
    half_bathrooms: number;
    total_bathrooms: number;
    lot_size: number;
    building_area: number;
    year_built: string;
    floors: number;
    pool: boolean;
    garages: number;
    sales_status: string;
    sales_date: string;
    sales_listing_price: number;
    sales_closing_price: number;
    sales_days_on_market: number;
    rents_status: string | null;
    rents_date: string | null;
    rents_listing_price: number | null;
    rents_closing_price: number | null;
    rents_days_on_market: number | null;
    tax: number | null;
}

export default FullProperty;